# see https://github.com/geoserver/docker/tree/master
version: '3'
services: 
  db:
    restart: unless-stopped
    image: kartoza/postgis:9.6-2.4
    #image: kartoza/postgis:$POSTGRES_MAJOR_VERSION-$POSTGIS_MAJOR_VERSION.${POSTGIS_MINOR_RELEASE}
    volumes:
      #- postgres_data:/var/lib/postgresql/data/
      # kartoza-postgis dockerhub recommends mounting the parent location. This is different from other postgres images
      - postgres_data:/var/lib/postgresql
      - postgres_pgconf:/etc/postgresql
      - postgres_pglog:/var/log/postgresql
    env_file:
      #- ./.env.prod.db
      # - ./.env.prod
      # .env ensures we can use environment variables within docker-compose. Else any other file will not make the variables accessible
      - .env
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DBNAME=${POSTGRES_DBNAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASS=${POSTGRES_PASS}
      #   - POSTGRES_MAJOR_VERSION=${POSTGRES_MAJOR_VERSION}
      #   - POSTGIS_MAJOR_VERSION=${POSTGIS_MAJOR_VERSION}
      #   - POSTGIS_MINOR_RELEASE=${POSTGIS_MINOR_RELEASE}
  geoserver:
    image: kartoza/geoserver:2.20.1
    restart: always
    ports:
      - "8600:8080"
    environment:
      - GEOSERVER_DATA_DIR=${GEOSERVER_DATA_DIR}
      - GEOWEBCACHE_CACHE_DIR=${GEOWEBCACHE_CACHE_DIR}
      - GEOSERVER_ADMIN_PASSWORD=${GEOSERVER_ADMIN_PASSWORD}
      - GEOSERVER_ADMIN_USER=${GEOSERVER_ADMIN_USER}
      - RESET_ADMIN_CREDENTIALS=${RESET_ADMIN_CREDENTIALS}
      - INITIAL_MEMORY=${INITIAL_MEMORY}
      - MAXIMUM_MEMORY=${MAXIMUM_MEMORY}
    volumes:
      #- geoserver_data:/opt/geoserver/data_dir 
      - geoserver_data:${GEOSERVER_DATA_DIR}
    env_file: 
      - .env
    links:
      - db
volumes:
  postgres_data:
  postgres_pgconf:
  postgres_pglog:
  # static_volume:
  # media_volumes:
  #   driver: local
  #   driver_opts:
  #     type: 'none'
  #     o: 'bind'
  #     device: '/home/ubuntu/oss_ldms_media'
  # dataset_volumes:
  #   driver: local
  #   driver_opts:
  #     type: 'none'
  #     o: 'bind'
  #     device: '/home/ubuntu/datasets'
  # redisdata:
  geoserver_data:
  # db-backups: